build.gradle
src/main/java/com/smeme/server/SmemeServerRenewalApplication.java
src/main/java/com/smeme/server/controllers/TestController.java
src/main/resources/application.properties
src/main/resources/application.yml

- closed #3 
- 서버 연결 테스트 API 구현

[FEAT] 서버 연결 테스트 API 구현

---

src/main/java/com/smeme/server/controllers/DiaryController.java
src/main/java/com/smeme/server/dtos/diary/DiaryPublicDetailFindResponseDto.java
src/main/java/com/smeme/server/services/DiaryService.java

- closed #11 
- PR 및 충돌 이슈의 발생 가능성을 고려해서, 9번 브랜치에서 이어서 11번 브랜치 작업에서 진행 후, 9번 브랜치로 PR 날립니다. 9번 및 11번 approve 나면 한번에 develop으로 머지하겠습니다!

[FEAT] 게시판 일기 상세조회 기능 구현

---

src/main/java/com/smeme/server/controllers/DiaryController.java
src/main/java/com/smeme/server/controllers/GlobalControllerAdvice.java
src/main/java/com/smeme/server/dtos/diary/DiariesPublicFindResponseDto.java
src/main/java/com/smeme/server/dtos/diary/DiaryPublicDetailFindResponseDto.java
src/main/java/com/smeme/server/dtos/diary/DiaryPublicFindRequestDto.java
src/main/java/com/smeme/server/dtos/diary/DiaryPublicFindResponseDto.java
src/main/java/com/smeme/server/repositories/CategoryRepository.java
src/main/java/com/smeme/server/repositories/DiaryRepository.java
src/main/java/com/smeme/server/repositories/TopicRepository.java
src/main/java/com/smeme/server/services/DiaryService.java

- closed #9 
- 게시판 일기 리스트를 조회하는 API 기능을 구현했습니다. (리팩토링)

[FEAT] 게시판 조회 기능 구현

---

src/main/java/com/smeme/server/controllers/TopicController.java
src/main/java/com/smeme/server/dtos/topic/TopicResponseDto.java
src/main/java/com/smeme/server/services/TopicService.java

- closed #19 
- 랜덤 주제 조회 기능을 리팩토링 구현했습니다.

[FEAT] 랜덤 주제 조회 기능 구현

---

src/main/java/com/smeme/server/controllers/ScrapController.java
src/main/java/com/smeme/server/dtos/scrap/ScrapRequestDto.java
src/main/java/com/smeme/server/dtos/scrap/ScrapResponseDto.java
src/main/java/com/smeme/server/models/Scrap.java
src/main/java/com/smeme/server/repositories/ScrapRepository.java
src/main/java/com/smeme/server/services/ScrapService.java

- closed #15 
- 스크랩 구문 저장 기능을 리팩토링 구현했습니다.

[FEAT] 스크랩 구문 저장 기능 구현

---

src/main/java/com/smeme/server/controllers/ScrapController.java
src/main/java/com/smeme/server/dtos/scrap/ScrapFindRequestDto.java
src/main/java/com/smeme/server/dtos/scrap/ScrapFindResponseDto.java
src/main/java/com/smeme/server/dtos/scrap/ScrapsFindResponseDto.java
src/main/java/com/smeme/server/repositories/ScrapRepository.java
src/main/java/com/smeme/server/services/ScrapService.java

- closed #17 
- 스크랩 리스트 조회 기능 리팩토링 구현 했습니다.

[FEAT] 스크랩 리스트 조회 기능 구현

---

src/main/java/com/smeme/server/controllers/DiaryController.java
src/main/java/com/smeme/server/dtos/diary/DiaryLikeRequestDto.java
src/main/java/com/smeme/server/dtos/diary/DiaryLikeResponseDto.java
src/main/java/com/smeme/server/repositories/LikeRepository.java
src/main/java/com/smeme/server/services/DiaryService.java

- closed #21 
- 게시판 일기 추천 리팩토링 기능 구현했습니다.

[FEAT] 게시판 일기 추천 기능 구현

---

src/main/java/com/smeme/server/controllers/CategoryController.java
src/main/java/com/smeme/server/dtos/category/CategoriesResponseDto.java
src/main/java/com/smeme/server/dtos/category/CategoryResponseDto.java
src/main/java/com/smeme/server/repositories/CategoryRepository.java
src/main/java/com/smeme/server/services/CategoryService.java

- closed #24 
- 카테고리 전체 조회 기능 리팩토링 구현했습니다.

[FEAT] 카테고리 전체 조회 기능 구현

---

src/main/java/com/smeme/server/controllers/ScrapController.java
src/main/java/com/smeme/server/services/ScrapService.java
src/main/java/com/smeme/server/utils/ApiResponse.java

- closed #26 
- 스크랩 삭제 기능을 리팩토링 구현했습니다.

[FEAT] 스크랩 삭제 기능 구현

---

src/main/java/com/smeme/server/controllers/DiaryController.java
src/main/java/com/smeme/server/controllers/ScrapController.java
src/main/java/com/smeme/server/dtos/diary/DiaryCreateRequestDto.java
src/main/java/com/smeme/server/dtos/diary/DiaryLikeRequestDto.java
src/main/java/com/smeme/server/dtos/diary/DiaryPublicFindRequestDto.java
src/main/java/com/smeme/server/dtos/scrap/ScrapFindRequestDto.java
src/main/java/com/smeme/server/dtos/scrap/ScrapRequestDto.java
src/main/java/com/smeme/server/services/DiaryService.java
src/main/java/com/smeme/server/services/ScrapService.java
src/main/java/com/smeme/server/services/UserService.java
src/test/java/com/smeme/server/services/DiaryServiceTest.java

- closed #33 
- Principal을 사용하는 user 검증 로직으로 전체적으로 변경하였습니다.

[FIX] Principal 적용

---

.github/workflows/deploy.yml
gradle/wrapper/gradle-wrapper.properties
src/main/resources/application.yml

- closed #36 
- CICD - CI TEST

[ADD] CI: deploy 파일 추가

---

.gitignore
build.gradle
src/main/java/com/smeme/server/config/SecurityConfig.java
src/test/java/com/smeme/server/SmemeServerRenewalApplicationTests.java

- closed #40 
1. Swagger 3 설정
- Swagger의 경우 기존 `springfox`를 사용하는 걸로 알고 있었는데, springboot3 이상에서 dependency의 문제가 있는 것 같습니다.
- 따라서 `springdoc`에서 제공하는 swagger 라이브러리로 설치했습니다. 
2. Jacoco 설정

[CHORE] Swagger3 , Jacoco 세팅

---

build.gradle
src/main/java/com/smeme/server/config/JpaQueryFactoryConfig.java
src/main/java/com/smeme/server/controller/DiaryController.java
src/main/java/com/smeme/server/controller/ErrorHandler.java
src/main/java/com/smeme/server/dto/diary/DiaryRequestDTO.java
src/main/java/com/smeme/server/model/Diary.java
src/main/java/com/smeme/server/model/topic/Category.java
src/main/java/com/smeme/server/repository/MemberRepository.java
src/main/java/com/smeme/server/repository/TopicRepository.java
src/main/java/com/smeme/server/repository/diary/DiaryCustomRepository.java
src/main/java/com/smeme/server/repository/diary/DiaryRepository.java
src/main/java/com/smeme/server/repository/diary/DiaryRepositoryImpl.java
src/main/java/com/smeme/server/service/DiaryService.java
src/main/java/com/smeme/server/util/message/ErrorMessage.java
src/main/java/com/smeme/server/util/message/ResponseMessage.java

- closed #49 
- 일기 작성 **기능 구현**
- **QueryDSL** 설정
- **MemberRepository, TopicRepository** 필요에 의해 생성
- **예외 처리** Controller 추가

[FEAT] 일기 작성 기능 구현

---

src/main/java/com/smeme/server/config/jwt/JwtTokenFilter.java
src/main/java/com/smeme/server/config/jwt/JwtTokenProvider.java
src/main/java/com/smeme/server/controller/AuthController.java
src/main/java/com/smeme/server/dto/auth/SignInRequestDTO.java
src/main/java/com/smeme/server/dto/auth/SignInResponseDTO.java
src/main/java/com/smeme/server/dto/auth/token/TokenResponseDTO.java
src/main/java/com/smeme/server/model/Member.java
src/main/java/com/smeme/server/repository/MemberRepository.java
src/main/java/com/smeme/server/service/auth/AppleSignIn.java
src/main/java/com/smeme/server/service/auth/AuthService.java
src/main/java/com/smeme/server/service/auth/KakaoSignIn.java
src/main/java/com/smeme/server/util/message/ErrorMessage.java
src/main/java/com/smeme/server/util/message/ResponseMessage.java

- closed #46 
- Apple, Kakao 소셜로그인을 구현했습니다. AuthService에서 전부관리하려다 code가 너무 길어져서, 소셜플랫폼 별로 class를 뻈는데, 좋은 설계를 위해서 리팩토링 하는게 좋을 것 같습니다...

[FEAT] 소셜 로그인 API 구현

---

src/main/java/com/smeme/server/controller/AuthController.java
src/main/java/com/smeme/server/service/auth/AuthService.java
src/main/java/com/smeme/server/util/message/ResponseMessage.java

- closed #59 
- 로그아웃 API를 구현했습니다. 
- 소셜로그인 API Util.getMemberId() 사용하도록 리팩토링

[FEAT] 로그아웃 API 구현

---

src/main/java/com/smeme/server/controller/CorrectionController.java
src/main/java/com/smeme/server/controller/DiaryController.java
src/main/java/com/smeme/server/dto/correction/CorrectionRequestDTO.java
src/main/java/com/smeme/server/service/CorrectionService.java
src/main/java/com/smeme/server/util/Util.java
src/main/java/com/smeme/server/util/message/ResponseMessage.java

- closed #63 
- 첨삭 기능 구현했습니다.
- getURI 통일화 및 일기 작성 메소드에 반영했습니다.

[FEAT] 첨삭 기능 구현

---

src/main/java/com/smeme/server/controller/CorrectionController.java
src/main/java/com/smeme/server/model/Correction.java
src/main/java/com/smeme/server/service/CorrectionService.java
src/main/java/com/smeme/server/util/message/ErrorMessage.java
src/main/java/com/smeme/server/util/message/ResponseMessage.java

- closed #67 
- 첨삭 제거 기능을 구현했습니다.
- ErrorMessage 파일에서 tab 크기 관련 코드 스타일이 다른 부분이 있어 일부 수정했습니다.

[FEAT] 첨삭 제거 기능 구현

---

src/main/java/com/smeme/server/controller/CorrectionController.java
src/main/java/com/smeme/server/model/Correction.java
src/main/java/com/smeme/server/service/CorrectionService.java
src/main/java/com/smeme/server/util/message/ResponseMessage.java

- closed #70 
- 첨삭 수정 기능을 구현했습니다.

[FEAT] 첨삭 수정 기능 구현

---

src/main/java/com/smeme/server/controller/ErrorHandler.java
src/main/java/com/smeme/server/service/CorrectionService.java
src/main/java/com/smeme/server/service/DiaryService.java

- closed #77 
- Swagger + RestDocs 과정 중 NotFoundException 충돌 관련 이슈를 해결했습니다.
- NotFoundException 예외를 사용하던 메소드에서 NoSuchElementException 예외로 변경했습니다.

[FIX] 예외 처리 변경

---

src/main/java/com/smeme/server/controller/ErrorHandler.java

[CHORE] exception handler method명 변경

---

src/main/java/com/smeme/server/model/badge/BadgeType.java
src/main/java/com/smeme/server/model/goal/GoalType.java
src/main/java/com/smeme/server/model/topic/Category.java

- closed #85 
- 뱃지(Badge)/목표(Goal)/랜덤주제(Topic) 관련 더미데이터 1차 작업 완료했습니다.

[CHORE] 더미데이터 작업

---

src/main/java/com/smeme/server/repository/trainingTime/TrainingTimeRepositoryImpl.java

- closed #84 
- 푸시알람 대상 조회에서 "푸시알람에 동의한 회원" 조건을 추가했습니다.

[FIX] 푸시알람 대상 조회 쿼리 수정

---

build.gradle
src/main/java/com/smeme/server/config/SecurityConfig.java
src/main/java/com/smeme/server/config/jwt/CustomJwtAuthenticationEntryPoint.java
src/main/java/com/smeme/server/config/jwt/JwtAuthenticationFilter.java
src/main/java/com/smeme/server/config/jwt/JwtTokenProvider.java
src/main/java/com/smeme/server/controller/ErrorHandler.java
src/main/java/com/smeme/server/service/auth/AppleSignInService.java
src/main/java/com/smeme/server/service/auth/AuthService.java
src/main/resources/static/docs/open-api-3.0.1.json
src/test/java/com/smeme/server/SmemeServerRenewalApplicationTests.java
src/test/java/com/smeme/server/controller/BaseControllerTest.java
src/test/java/com/smeme/server/controller/TestControllerTest.java

- closed #74 
- Access Token을 넣지 않아도, 요청이 들어가던 문제를 수정했습니다.
- Token 없이 요청을 날리는 경우.
다음과 같은 Message를 출력합니다.

[REFACTOR] JWT security 관련 로직 수정

---

src/main/java/com/smeme/server/config/jwt/JwtTokenProvider.java
src/main/java/com/smeme/server/controller/BadgeController.java
src/main/java/com/smeme/server/dto/badge/BadgeListResponseDTO.java
src/main/java/com/smeme/server/dto/badge/BadgeResponseDTO.java
src/main/java/com/smeme/server/dto/diary/DiariesResponseDTO.java
src/main/java/com/smeme/server/model/badge/Badge.java
src/main/java/com/smeme/server/model/badge/MemberBadge.java
src/main/java/com/smeme/server/repository/BadgeRepository.java
src/main/java/com/smeme/server/repository/MemberBadgeRepository.java
src/main/java/com/smeme/server/service/BadgeService.java
src/main/java/com/smeme/server/util/message/ResponseMessage.java

- closed #94 
- 뱃지 목록 조회 API를 구현헀습니다.
- JwtProvider에서 Int를 Long으로 Casting 하지 못해서, String으로 바꾼후 Parsing하게 수정했습니다.

[ADD] 뱃지 목록 조회 API 구현

---

src/main/java/com/smeme/server/controller/CorrectionController.java
src/main/java/com/smeme/server/controller/DiaryController.java
src/main/java/com/smeme/server/dto/correction/CorrectionResponseDTO.java
src/main/java/com/smeme/server/dto/diary/CreatedDiaryResponseDTO.java
src/main/java/com/smeme/server/repository/MemberBadgeRepository.java
src/main/java/com/smeme/server/repository/correction/CorrectionCustomRepository.java
src/main/java/com/smeme/server/repository/correction/CorrectionRepository.java
src/main/java/com/smeme/server/repository/correction/CorrectionRepositoryImpl.java
src/main/java/com/smeme/server/repository/diary/DiaryCustomRepository.java
src/main/java/com/smeme/server/repository/diary/DiaryRepositoryImpl.java
src/main/java/com/smeme/server/service/BadgeService.java
src/main/java/com/smeme/server/service/CorrectionService.java
src/main/java/com/smeme/server/service/DiaryService.java
src/main/java/com/smeme/server/util/message/ErrorMessage.java

- closed #90 
- 일기 작성 누적 수 및 연속 수 관련 뱃지 획득 로직 추가
- 첨삭 누적 수 관련 뱃지 획득 로직 추가
- 일기 관련 쿼리에서 diary.isDeleted = false 조건 추가

[ADD] 뱃지 획득 로직 추가

---

src/main/java/com/smeme/server/config/SecurityConfig.java
src/main/java/com/smeme/server/controller/BadgeController.java
src/main/java/com/smeme/server/controller/BetaAuthController.java
src/main/java/com/smeme/server/controller/MemberController.java
src/main/java/com/smeme/server/dto/auth/beta/BetaTokenResponseDTO.java
src/main/java/com/smeme/server/dto/member/MemberPlanUpdateRequestDTO.java
src/main/java/com/smeme/server/dto/training/TrainingTimeRequestDTO.java
src/main/java/com/smeme/server/model/Member.java
src/main/java/com/smeme/server/model/SocialType.java
src/main/java/com/smeme/server/model/training/TrainingTime.java
src/main/java/com/smeme/server/service/MemberService.java
src/main/java/com/smeme/server/service/auth/BetaAuthService.java
src/main/java/com/smeme/server/util/message/ResponseMessage.java

[CHORE] 마이페이지 조회 API Response 수정

---

src/main/java/com/smeme/server/config/SecurityConfig.java
src/main/java/com/smeme/server/controller/MemberController.java
src/main/java/com/smeme/server/dto/member/MemberNameResponseDTO.java
src/main/java/com/smeme/server/service/MemberService.java
src/main/java/com/smeme/server/util/message/ResponseMessage.java

- closed #111 
- 닉네임 중복 검사 API 구현했습니다.
- 토큰 검사 X

[FEAT] 닉네임 중복 검사

---

src/main/java/com/smeme/server/config/SecurityConfig.java
src/main/java/com/smeme/server/controller/GoalController.java
src/main/java/com/smeme/server/dto/goal/GoalResponseDTO.java
src/main/java/com/smeme/server/service/GoalService.java
src/main/java/com/smeme/server/util/message/ResponseMessage.java

- closed #113 
- 학습 목표 상세 조회
- 토큰 검사 X

[FEAT] 학습 목표 상세 조회

---

src/main/java/com/smeme/server/controller/TestController.java
src/main/java/com/smeme/server/service/MessageService.java

- closed #121 
- 푸시 알림 테스트용 API
- 토큰 유저에게 푸시 알림을 전송합니다.

[FEAT] 푸시 알림 테스트 API

---

src/main/java/com/smeme/server/controller/ScheduleController.java
src/main/java/com/smeme/server/service/MemberService.java
src/main/java/com/smeme/server/service/MessageService.java

- closed #126 
- 푸쉬 알림 message를 임시 값에서 베타 테스트 용으로 수정합니다.
- TrainingTime이 저장되어 있지 않은 경우 마이페이지 조회에서 404가 발생하여, 임시 값을 넣어 response 해주는 형태로 리팩토링 진행했습니다. Beta test이후에는 수정이 필요할 것 같습니다!

[FIX] 푸쉬 알림 message 변경

---

src/main/java/com/smeme/server/controller/AuthController.java
src/main/java/com/smeme/server/controller/BadgeController.java
src/main/java/com/smeme/server/controller/BetaAuthController.java
src/main/java/com/smeme/server/controller/MemberController.java
src/main/java/com/smeme/server/dto/auth/SignInRequestDTO.java
src/main/java/com/smeme/server/dto/auth/SignInResponseDTO.java
src/main/java/com/smeme/server/dto/auth/beta/BetaSignInRequestDTO.java
src/main/java/com/smeme/server/dto/auth/beta/BetaTokenResponseDTO.java
src/main/java/com/smeme/server/dto/badge/BadgeResponseDTO.java
src/main/java/com/smeme/server/dto/member/MemberGetResponseDTO.java
src/main/java/com/smeme/server/dto/member/MemberNameResponseDTO.java
src/main/java/com/smeme/server/dto/member/MemberPlanUpdateRequestDTO.java
src/main/java/com/smeme/server/dto/member/MemberUpdateRequestDTO.java
src/main/java/com/smeme/server/service/auth/AuthService.java
src/main/resources/static/docs/open-api-3.0.1.json

- closed #129 
Auth ✅
Badge ✅
BetaAuth ✅
Member ✅

[DOCS] Swagger 정보 추가

---

src/main/java/com/smeme/server/controller/AuthController.java
src/main/java/com/smeme/server/repository/MemberRepository.java
src/main/java/com/smeme/server/repository/badge/MemberBadgeRepository.java
src/main/java/com/smeme/server/repository/correction/CorrectionRepository.java
src/main/java/com/smeme/server/repository/diary/DiaryRepository.java
src/main/java/com/smeme/server/repository/trainingTime/TrainingTimeRepository.java
src/main/java/com/smeme/server/service/auth/AuthService.java
src/main/java/com/smeme/server/util/message/ResponseMessage.java

- closed #134 
- 회원 탈퇴를 진행하는 API를 개발했습니다.

[FEAT] 회원 탈퇴 API 개발

---

src/main/java/com/smeme/server/dto/auth/SignInResponseDTO.java

- closed #135 
- 소셜로그인 API response body에서 badge를 삭제했습니다.

[CHORE] SiginInRepsonseDTO response body 삭제

---

src/main/java/com/smeme/server/dto/auth/SignInResponseDTO.java
src/main/java/com/smeme/server/service/auth/AuthService.java

- closed #142 
해당 PR의 요구사항 참고
https://github.com/Team-Smeme/smeem-aos/issues/99
- member가 목표를 갖고 있는지를 여부로 hasPlan data를 다시 추가했습니다.

[REFACTOR] social login api hasPlan 추가

---

src/main/java/com/smeme/server/controller/ScheduleController.java

- closed #155 
- prod 서버 스케줄러 임시 중단합니다. (푸시알림 중복 이슈)

[CHORE] prod 스케줄러 임시 중단

---

src/main/java/com/smeme/server/model/Member.java

- closed #161 
- 일기 연속 작성 수를 데이터로 관리하기 위해 해당 칼럼을 추가했습니다. (dev 반영, 해당 PR 머지 후 prod 반영 예정)

[ADD] Member 칼럼 추가

---

src/main/java/com/smeme/server/config/ValueConfig.java
src/main/java/com/smeme/server/controller/CorrectionController.java
src/main/java/com/smeme/server/controller/DiaryController.java
src/main/java/com/smeme/server/controller/ErrorHandler.java
src/main/java/com/smeme/server/controller/GoalController.java
src/main/java/com/smeme/server/controller/ScheduleController.java
src/main/java/com/smeme/server/controller/TopicController.java
src/main/java/com/smeme/server/dto/correction/CorrectionResponseDTO.java
src/main/java/com/smeme/server/dto/diary/DiariesResponseDTO.java
src/main/java/com/smeme/server/dto/diary/DiaryResponseDTO.java
src/main/java/com/smeme/server/model/Correction.java
src/main/java/com/smeme/server/model/Diary.java
src/main/java/com/smeme/server/model/Member.java
src/main/java/com/smeme/server/repository/correction/CorrectionCustomRepository.java
src/main/java/com/smeme/server/repository/correction/CorrectionRepositoryImpl.java
src/main/java/com/smeme/server/repository/diary/DiaryCustomRepository.java
src/main/java/com/smeme/server/repository/diary/DiaryRepositoryImpl.java
src/main/java/com/smeme/server/repository/topic/TopicCustomRepository.java
src/main/java/com/smeme/server/repository/topic/TopicRepositoryImpl.java
src/main/java/com/smeme/server/service/BadgeService.java
src/main/java/com/smeme/server/service/CorrectionService.java
src/main/java/com/smeme/server/service/DiaryService.java
src/main/java/com/smeme/server/service/GoalService.java
src/main/java/com/smeme/server/service/MemberService.java
src/main/java/com/smeme/server/service/TopicService.java
src/main/java/com/smeme/server/util/Util.java

- closed #158 
- 담당한 기능 리팩토링 작업을 진행했습니다.

[REFACT] 리팩토링

---

src/main/java/com/smeme/server/model/topic/Category.java
src/main/resources/static/docs/open-api-3.0.1.json

- closed #173 
- 랜덤주제 카테고리가 추가되었습니다. (DAILY, 일상)

[ADD] 랜덤주제 카테고리 추가

---

src/main/java/com/smeme/server/model/goal/Goal.java

- closed #178 
- Goal 엔티티 기본 생성자 추가

[HOTFIX] 목표 조회 에러 대응

---

src/main/java/com/smeme/server/dto/badge/BadgeListResponseDTO.java
src/main/java/com/smeme/server/dto/badge/BadgeResponseDTO.java
src/main/java/com/smeme/server/handler/ErrorHandler.java
src/main/java/com/smeme/server/model/badge/Badge.java
src/main/java/com/smeme/server/repository/badge/MemberBadgeRepository.java
src/main/java/com/smeme/server/service/BadgeService.java
src/main/resources/static/docs/open-api-3.0.1.json
src/test/java/com/smeme/server/controller/BadgeControllerTest.java
src/test/java/com/smeme/server/fixture/badge/BadgeFixture.java
src/test/java/com/smeme/server/fixture/member/MemberFixture.java

- closed #187 
- **직전 PR과 중복되는 내용이 있어 직전 PR 병합 후 코드 리뷰 부탁드려요!**
- 뱃지 전체 조회(뱃지 있으면 컬러, 없으면 흑백) 기능을 수정했습니다.
- Fixture 및 Test 코드 일부 수정했습니다.
- 일부 사용하지 않는 코드들을 삭제했습니다.

[FIX] 뱃지 전체 조회로 수정

---

src/main/java/com/smeme/server/dto/badge/AcquiredBadgeResponseDTO.java
src/main/java/com/smeme/server/dto/diary/CreatedDiaryResponseDTO.java
src/main/java/com/smeme/server/dto/member/MemberUpdateResponseDTO.java
src/main/resources/static/docs/open-api-3.0.1.json
src/test/java/com/smeme/server/controller/DiaryControllerTest.java

- closed #191 
- 획득한 뱃지 데이터에 타입을 추가했습니다.

[ADD] 획득한 뱃지에 타입 데이터 추가

---

smeem-api/src/main/java/com/smeem/api/auth/controller/AuthController.java
smeem-api/src/main/java/com/smeem/api/auth/controller/dto/response/SignInResponse.java
smeem-api/src/main/java/com/smeem/api/auth/jwt/TokenProvider.java
smeem-api/src/main/java/com/smeem/api/auth/service/dto/response/TokenServiceResponse.java
smeem-api/src/main/java/com/smeem/api/badge/controller/BadgeController.java
smeem-api/src/main/java/com/smeem/api/badge/controller/dto/response/BadgeResponse.java
smeem-api/src/main/java/com/smeem/api/member/controller/dto/response/MemberNameResponse.java
smeem-api/src/main/java/com/smeem/api/member/controller/dto/response/TrainingTimeResponse.java

- closed #198 
- 1차 리팩토링 이후에 리뷰 받은 내용을 기반으로 리팩토링을 진행헀습니다.

[REFACTOR] 2차 리팩토링 

---

build.gradle
smeem-api/src/main/java/com/smeem/api/config/SecurityConfig.java
smeem-common/src/main/java/com/smeem/common/code/failure/FcmFailureCode.java
smeem-common/src/main/java/com/smeem/common/exception/FcmException.java
smeem-external/src/main/java/com/smeem/external/firebase/FcmService.java

none
- 외부 API 호출 OkHttp -> RestClient 리팩토링 작업
- 스프링 3.2.0 버전업
- SecurityConfig 람다식 수정 및 일부 리팩토링
<br/>
관련 참고 레퍼런스 아래에 추가해두겠습니다 :)
https://mangkyu.tistory.com/303

[REFACTOR] RestClient 사용 및 그 외

---

scripts/run_new_was.sh

- closed #211 
- 배포 실패 대응, jar 파일 경로 수정

[FIX] jar 파일 경로 수정

---

scripts/health_check.sh

[FIX] 테스트 URI 수정

---

smeem-api/src/main/java/com/smeem/api/common/advicer/ErrorHandler.java
smeem-api/src/main/java/com/smeem/api/member/service/MemberService.java
smeem-api/src/main/resources/application-dev.yml
smeem-api/src/main/resources/application-local.yml
smeem-api/src/main/resources/application-prod.yml
smeem-common/src/main/java/com/smeem/common/code/failure/InternalServerFailureCode.java
smeem-common/src/main/java/com/smeem/common/config/ValueConfig.java
smeem-external/src/main/java/com/smeem/external/discord/DiscordAlarmCase.java
smeem-external/src/main/java/com/smeem/external/discord/DiscordAlarmSender.java
smeem-external/src/main/java/com/smeem/external/discord/DiscordRequest.java

- closed #215
- 디스코드 알람을 구현 했습니다.
- 핸들링 하지 못하는 상황과 회원가입 시에 디스코드에 알람을 보낼 수 있도록 구현했습니다.

[FEAT] Discord 알람 구현

---

smeem-api/src/main/java/com/smeem/api/goal/controller/dto/response/GoalGetResponse.java
smeem-api/src/main/java/com/smeem/api/goal/service/dto/response/GoalGetServiceResponse.java
smeem-api/src/main/java/com/smeem/api/member/controller/dto/response/MemberGetResponse.java
smeem-api/src/main/java/com/smeem/api/member/service/dto/response/MemberGetServiceResponse.java

- closed #222 
- `수정 API`: 회원 프로필 조회, 목표 상세 조회
- 클라이언트와 합의한 후, 각 목표의 description 값을 title 필드로 추가했습니다.

[ADD] 목표 제목 추가

---

smeem-api/src/main/java/com/smeem/api/diary/api/DiaryApi.java
smeem-api/src/main/java/com/smeem/api/diary/api/DiaryApiController.java
smeem-api/src/main/java/com/smeem/api/diary/api/dto/request/DiaryCreateRequest.java
smeem-api/src/main/java/com/smeem/api/diary/api/dto/request/DiaryModifyRequest.java
smeem-api/src/main/java/com/smeem/api/diary/api/dto/response/DiaryCreateResponse.java
smeem-api/src/main/java/com/smeem/api/diary/api/dto/response/DiaryGetResponse.java
smeem-api/src/main/java/com/smeem/api/diary/api/dto/response/DiaryListGetResponse.java
smeem-api/src/main/java/com/smeem/api/diary/service/dto/request/DiaryCreateServiceRequest.java
smeem-api/src/main/java/com/smeem/api/diary/service/dto/request/DiaryModifyServiceRequest.java
smeem-api/src/main/java/com/smeem/api/goal/api/GoalApi.java
smeem-api/src/main/java/com/smeem/api/goal/api/GoalApiController.java
smeem-api/src/main/java/com/smeem/api/goal/api/dto/response/GoalGetResponse.java
smeem-api/src/main/java/com/smeem/api/goal/api/dto/response/GoalListGetResponse.java
smeem-api/src/main/java/com/smeem/api/test/api/TestApi.java
smeem-api/src/main/java/com/smeem/api/topic/api/TopicApi.java
smeem-api/src/main/java/com/smeem/api/topic/api/TopicApiController.java
smeem-api/src/main/java/com/smeem/api/topic/api/dto/response/RandomTopicGetResponse.java
smeem-api/src/test/java/com/smeem/api/controller/DiaryControllerTest.java

- closed #186 
- 스웨거 이사를 위해 각 담당 도메인의 api 인터페이스 추가했습니다.
- diary
- goal
- topic
- test

[REFACTOR] 스웨거 이사

---

smeem-api/src/main/java/com/smeem/api/auth/api/AuthApi.java
smeem-api/src/main/java/com/smeem/api/auth/api/AuthController.java

- #228 
- AuthController에서 AuthAPI implements를 구현하도록 수정했습니다.

[CHORE] Auth API implements 키워드 추가

---

smeem-api/src/main/java/com/smeem/api/common/schedulerTemp/DiaryScheduler.java
smeem-api/src/main/java/com/smeem/api/common/schedulerTemp/MessageScheduler.java

- closed #240 
- 스케줄러가 batch 모듈 내에서 동작되지 않아, 우선 prod 서버에서만 api 모듈 내 스케줄러 파일을 이동합니다. (해결 후 복구 예정)

[HOTFIX] 스케줄러 임시 이동

---

README.md

- none
- 몇몇 내용 추가/정리 작업 진행했습니다~

[ADD] 사이드 요소 추가 및 정리

---

README.md

[DOCS] README.md 작성

---

README.md

- none
- 간지나는 디자인 선생님이 그려주신 이미지로 수정 완료 ⭐️

[FIX] 서비스 개요 이미지 수정

---

smeem-api/src/main/java/com/smeem/api/member/api/MemberApi.java
smeem-api/src/main/java/com/smeem/api/member/api/MemberController.java
smeem-api/src/main/java/com/smeem/api/member/api/dto/response/MemberPerformanceGetResponse.java
smeem-api/src/main/java/com/smeem/api/member/service/MemberService.java
smeem-api/src/main/java/com/smeem/api/member/service/dto/request/MemberPerformanceGetServiceRequest.java
smeem-api/src/main/java/com/smeem/api/member/service/dto/response/MemberPerformanceGetServiceResponse.java
smeem-api/src/main/java/com/smeem/api/version/api/VersionApi.java
smeem-common/src/main/java/com/smeem/common/code/success/MemberSuccessCode.java
smeem-domain/src/main/java/com/smeem/domain/member/model/DiaryComboInfo.java
smeem-domain/src/main/java/com/smeem/domain/member/model/Member.java
smeem-domain/src/main/java/com/smeem/domain/member/model/MemberVisitInfo.java

- closed #257 
- 2차 스프린트 신규 기능 개발
- 성과 요약 페이지에서 나의 스밈 정보를 조회하는 API 개발
- 새로운 API를 추가하여 버전 업은 따로 진행하지 않았습니다. (해당 기능 v2 유지)
<br/>

[FEAT] 성과 요약 조회 API

---

smeem-api/src/main/java/com/smeem/api/member/api/MemberApi.java
smeem-api/src/main/java/com/smeem/api/member/api/MemberController.java
smeem-api/src/main/java/com/smeem/api/member/api/dto/response/MemberPlanGetResponse.java
smeem-api/src/main/java/com/smeem/api/member/service/MemberService.java
smeem-api/src/main/java/com/smeem/api/member/service/dto/request/MemberPlanGetServiceRequest.java
smeem-api/src/main/java/com/smeem/api/member/service/dto/response/MemberPlanGetServiceResponse.java
smeem-common/src/main/java/com/smeem/common/code/success/MemberSuccessCode.java
smeem-domain/src/main/java/com/smeem/domain/member/model/Member.java

- closed #259 
- 나의 플랜 조회 API 개발했습니다.
<br/>

[FEAT] 나의 플랜 조회 API

---

smeem-api/src/main/java/com/smeem/api/member/api/MemberApi.java
smeem-api/src/main/java/com/smeem/api/member/api/MemberController.java
smeem-api/src/main/java/com/smeem/api/member/service/MemberService.java
smeem-api/src/main/java/com/smeem/api/member/service/dto/request/MemberVisitUpdateRequest.java
smeem-common/src/main/java/com/smeem/common/code/success/MemberSuccessCode.java
smeem-domain/src/main/java/com/smeem/domain/member/model/Member.java
smeem-domain/src/main/java/com/smeem/domain/member/model/MemberVisitInfo.java

- closed #260 
- 방문일수를 기록하기 위한 API를 개발했습니다.
<br/>

[FEAT] 방문 체크 API

---

smeem-api/src/main/java/com/smeem/api/badge/api/dto/response/BadgeListResponseV3.java
smeem-api/src/main/java/com/smeem/api/badge/api/dto/response/BadgeResponseV3.java
smeem-api/src/main/java/com/smeem/api/badge/api/v2/BadgeV2Api.java
smeem-api/src/main/java/com/smeem/api/badge/api/v2/BadgeV2Controller.java
smeem-api/src/main/java/com/smeem/api/badge/api/v3/BadgeV3Api.java
smeem-api/src/main/java/com/smeem/api/badge/api/v3/BadgeV3Controller.java
smeem-api/src/main/java/com/smeem/api/badge/service/BadgeService.java
smeem-api/src/main/java/com/smeem/api/badge/service/dto/request/BadgeListServiceRequestV3.java
smeem-api/src/main/java/com/smeem/api/badge/service/dto/response/v3/BadgeGetServiceResponseV3.java
smeem-api/src/main/java/com/smeem/api/badge/service/dto/response/v3/BadgeListServiceResponseV3.java
smeem-api/src/main/resources/application-dev.yml
smeem-api/src/main/resources/application-local.yml
smeem-api/src/main/resources/application-prod.yml
smeem-batch/src/main/java/com/smeem/batch/scheduler/BadgeScheduler.java
smeem-batch/src/main/java/com/smeem/batch/scheduler/DiaryScheduler.java
smeem-batch/src/main/java/com/smeem/batch/scheduler/NotificationScheduler.java
smeem-batch/src/main/java/com/smeem/batch/scheduler/support/Scheduler.java
smeem-domain/src/main/java/com/smeem/domain/badge/adapter/BadgeFinder.java
smeem-domain/src/main/java/com/smeem/domain/badge/adapter/BadgeUpdater.java
smeem-domain/src/main/java/com/smeem/domain/badge/model/Badge.java
smeem-domain/src/main/java/com/smeem/domain/member/adapter/member/MemberCounter.java
smeem-domain/src/main/java/com/smeem/domain/member/adapter/memberbadge/MemberBadgeCounter.java
smeem-domain/src/main/java/com/smeem/domain/member/adapter/memberbadge/MemberBadgeFinder.java
smeem-domain/src/main/java/com/smeem/domain/member/repository/MemberBadgeRepository.java

- closed #265 
- 배지 목록 조회 API를 구현했습니다.
- Scheduling Script를 작성하는 클래스에서 특정 어노테이션을 반복해서 사용하고 있어서, 커스텀 어노테이션 `@Scheudler` 을 구현해서 분리했습니다. (괜찮으시다면 앞으로 어노테이션을 활용해도 좋을 것 같아요)
- Badge의 경우 획득 사용자 비율을 필드로 갖고 있고, 데이터가 변할 때마다 업데이트 하는 것이 아닌 한달에 한번 주기적으로 업데이트 하는 형태로 스펙이 결정되어, Scheduling 로직을 구현했습니다. 후처리 로직은 디코 참고해주시면 될 것 같아영 -> 날짜 조건은 없어서 우선 매달 1일 한번 새벽 4시에 업데이트 하는 걸로 구현했습니다~
- 일기 작성수에 따라 얻게되는 Badge는 조회에서 각 배지마다 획득하려면 얼마나 남았는지, 보여줘야 하기 때문에 해당 값은 `remainingNumber`에서 구현했습니다 ~ -> 구현한 코드가 깔끔하지는 않은 것 같은데 당장은 좋은 방법이 안 떠올라서, 좋은 방향을 제시해주시면 수정해보겠습니다. 배지수가 더 늘어난다고 해도, 수십개 안 쪽이어서 우선 성능은 크게 생각안하고 개발했습니다 ~  그 외에 배지들은 `remainingNumber`를 null로 return합니다. 
-
- 조금 애매한 부분이긴 한데 Count하는 method는 Finder보다 새롭게 클래스를 구성하는 것이  RepositoryAdapter에서 각 class의 의미를 더 담고 있는 것 같아서 (SRP 관점에서) Counter 클래스로 분리했습니다. 조회 로직이 많다보니, count 정도는 …

[FEAT] 배지 목록 조회 API 구현

---

smeem-api/src/main/java/com/smeem/api/member/api/dto/response/MemberGetResponse.java
smeem-api/src/main/java/com/smeem/api/member/api/dto/response/PlanResponse.java
smeem-api/src/main/java/com/smeem/api/member/service/MemberService.java
smeem-api/src/main/java/com/smeem/api/member/service/dto/response/MemberGetServiceResponse.java
smeem-api/src/main/java/com/smeem/api/member/service/dto/response/PlanServiceResponse.java

- closed #270 
- 사용자 정보 조회 API에서 Training Plan 필드를 내려받을 수 있도록 수정했습니다.
- nullable에 대비하여 WrappeType으로 바꾸고, 단일 객체여서 JSON data object안에 따로 object를 만들지는 않았습니다 ~ 필드명이나 format과 관련해서 리뷰해주시면 좋을 . 것같습니다 ~

[REFACTOR] 사용자 정보 조회 리팩토링

---

smeem-batch/src/main/java/com/smeem/batch/scheduler/BadgeScheduler.java

- closed #278 
- 배지 획득 비율 로직을 수정했습니다.

[FIX] 배지 획득 비율 후처리 로직 수정

---

smeem-api/src/main/java/com/smeem/api/member/service/MemberService.java
smeem-common/src/main/java/com/smeem/common/config/ValueConfig.java

- closed #283 
- 회원가입 알림 메세지 수정

[CHORE] 회원가입 알림 메세지 수정

---

README.md

[DOCS] 리드미 업데이트

---

smeem-api/src/main/java/com/smeem/api/version/api/dto/response/ClientVersionGetResponse.java

[ADD] 안드로이드 버전 추가

---

smeem-api/src/main/java/com/smeem/api/auth/service/AuthService.java
smeem-domain/src/main/java/com/smeem/domain/visit/adapter/VisitDeleter.java
smeem-domain/src/main/java/com/smeem/domain/visit/repository/VisitRepository.java

[HOTFIX] 회원탈퇴 이슈 대응

---

smeem-api/src/test/java/com/smeem/diary/service/DiaryCommandServiceTest.java
smeem-api/src/test/java/com/smeem/diary/service/integration/DiaryCommandServiceIntegrationTest.java
smeem-api/src/test/java/com/smeem/support/fixture/DiaryFixture.java
smeem-domain/src/main/java/com/smeem/domain/diary/model/Diary.java

- closed #294 
- 일기 수정 기능을 단위 테스트 코드로 작성했습니다.

[TEST] 일기 수정 테스트

---

smeem-application/src/main/java/com/smeem/application/domain/auth/AuthService.java

fix: protect login duplicated

---

smeem-application/src/main/java/com/smeem/application/domain/auth/AuthService.java
smeem-application/src/main/java/com/smeem/application/domain/withdraw/Withdraw.java
smeem-application/src/main/java/com/smeem/application/domain/withdraw/WithdrawType.java
smeem-application/src/main/java/com/smeem/application/port/input/AuthUseCase.java
smeem-application/src/main/java/com/smeem/application/port/input/dto/request/member/WithdrawRequest.java
smeem-application/src/main/java/com/smeem/application/port/output/persistence/MemberPort.java
smeem-bootstrap/src/main/resources/application-prod.yml
smeem-common/src/main/java/com/smeem/common/logger/LoggingMessage.java
smeem-input-http/src/main/java/com/smeem/http/controller/AuthApi.java
smeem-input-http/src/main/java/com/smeem/http/controller/docs/AuthApiDocs.java
smeem-output-persistence/postgresql/src/main/java/com/smeem/persistence/postgresql/adapter/MemberAdapter.java
smeem-output-persistence/postgresql/src/main/java/com/smeem/persistence/postgresql/persistence/entity/WithdrawEntity.java
smeem-output-persistence/postgresql/src/main/java/com/smeem/persistence/postgresql/persistence/repository/WithdrawRepository.java

- closed #313 
- 탈퇴 시 해당 사유를 수집합니다.
- 탈퇴 타입 정보
```
INSTABILITY("이용이 어렵고 서비스가 불안정해요."),
LACK("일기 작성을 도와주는 기능이 부족해요."),
BOTHER("일기 쓰기가 귀찮아요."),
COMPARISON("다른 앱이 사용하기 더 편해요."),
ETC("기타 의견"),
;
```

add: 탈퇴 사유 수집 기능 추가

---

smeem-application/src/main/java/com/smeem/application/domain/auth/AuthService.java
smeem-application/src/main/java/com/smeem/application/domain/member/Member.java
smeem-application/src/main/java/com/smeem/application/domain/member/MemberService.java
smeem-application/src/main/java/com/smeem/application/port/input/dto/response/auth/SignInResponse.java
smeem-input-http/src/main/java/com/smeem/http/controller/AuthApi.java

- closed #322 
- 로그인 과정에서 FCM 토큰을 매번 업데이트 합니다.
- 클라이언트 협업하여 테스트 후 해당 PR 머지합니다.

fix: 푸시알림 부재 이슈 대응

---

smeem-application/src/main/java/com/smeem/application/domain/diary/DiaryService.java
smeem-application/src/main/java/com/smeem/application/domain/member/MemberService.java
smeem-application/src/main/java/com/smeem/application/port/output/persistence/BadgePort.java
smeem-output-persistence/postgresql/src/main/java/com/smeem/persistence/postgresql/adapter/BadgeAdapter.java
smeem-output-persistence/postgresql/src/main/java/com/smeem/persistence/postgresql/adapter/DiaryAdapter.java

- closed #none
- QA 과정 중 발생한 이슈를 해결합니다.

hotfix: 0730 QA 이슈 해결

---

smeem-application/src/main/java/com/smeem/application/domain/member/MemberService.java
smeem-input-http/src/main/java/com/smeem/http/aspect/DuplicateRequestAspect.java

deploy: 실서버 배포

---

smeem-output-persistence/mongodb/src/main/java/com/smeem/output/persistence/mongodb/persistence/document/CorrectionDocument.java
smeem-output-persistence/postgresql/src/main/java/com/smeem/persistence/postgresql/persistence/entity/DiaryEntity.java

Deploy: deploy spring4 to prod server

---

smeem-application/src/main/java/com/smeem/application/domain/diary/DiaryService.java
smeem-application/src/main/java/com/smeem/application/port/input/dto/request/diary/WriteDiaryRequest.java

fix: updated update method

---

smeem-output-web/gpt/src/main/java/com/smeem/output/web/gpt/adapter/OpenAiAdapter.java
smeem-output-web/gpt/src/main/java/com/smeem/output/web/gpt/config/OpenAiConfig.java

fix: renamed ai method

---

smeem-application/src/main/java/com/smeem/application/port/input/dto/response/diary/CorrectionsResponse.java

- closed #361 
- added a true field in a correction response

[ADD] added a field in correction response

---

smeem-application/src/main/java/com/smeem/application/domain/diary/CorrectionService.java
smeem-application/src/main/java/com/smeem/application/port/input/dto/response/diary/CorrectionsResponse.java
smeem-application/src/main/java/com/smeem/application/port/output/persistence/CorrectionPort.java
smeem-output-persistence/mongodb/src/main/java/com/smeem/output/persistence/mongodb/adapter/CorrectionAdapter.java
smeem-output-persistence/mongodb/src/main/java/com/smeem/output/persistence/mongodb/persistence/repository/CorrectionRepository.java

- closed #364 
- 만족도 조사를 위한 임시 필드 추가

add: add fields for survey

---

smeem-output-persistence/postgresql/src/main/java/com/smeem/persistence/postgresql/persistence/entity/BookmarkEntity.java
smeem-output-web/scrap/src/main/java/com/smeem/output/web/scrap/ScrapAdapter.java

Remove Shortener URL Generator

---

smeem-application/src/main/java/com/smeem/application/domain/auth/AuthService.java

- closed #388 
- BookmarkPort 필드에 final 키워드를 추가하여 반드시 생성자 주입이 이루어지도록 변경했습니다. 이를 통해 스프링 DI 시점에서 의존성 누락이 발생하지 않도록 보장합니다.

[FIX] BookmarkPort를 final로 변경하여 생성자 주입 강제
