Team-Smeme/Smeme-server-renewal

src/main/java/com/smeme/server/controller/DiaryController.java
src/main/java/com/smeme/server/dto/diary/DiaryResponseDTO.java
src/main/java/com/smeme/server/repository/CorrectionRepository.java
src/main/java/com/smeme/server/service/DiaryService.java
src/main/java/com/smeme/server/util/message/ErrorMessage.java
src/main/java/com/smeme/server/util/message/ResponseMessage.java

- closed #51 
- 일기 상세 조회 기능을 구현했습니다.
- 클서 회의에서 결정한 내용대로 해당 기능에 **첨삭 리스트 데이터**를 추가했으며, 최신순 정렬로 id 역순 정렬로 설정했습니다.
- 랜덤주제(topic)이 null인 diary의 topic는 빈 값("") 처리했습니다.

[FEAT] 일기 상세 조회 API 구현

---

src/main/java/com/smeme/server/config/TimezoneConfig.java
src/main/java/com/smeme/server/controller/DiaryController.java
src/main/java/com/smeme/server/model/Diary.java
src/main/java/com/smeme/server/service/DiaryService.java
src/main/java/com/smeme/server/util/message/ResponseMessage.java

- closed #52 
- 일기 수정 기능을 구현했습니다.
- 수정할 경우, updatedAt 값도 업데이트 됩니다.
- Service 파일에 @Transactional(readOnly=true) 추가하고, 추가 및 수정 메소드에 @Transactional 어노테이션 추가했습니다.

[FEAT] 일기 수정 기능 구현

---

src/main/java/com/smeme/server/controller/DiaryController.java
src/main/java/com/smeme/server/controller/ErrorHandler.java
src/main/java/com/smeme/server/model/Diary.java
src/main/java/com/smeme/server/repository/diary/DiaryRepositoryImpl.java
src/main/java/com/smeme/server/service/DiaryService.java
src/main/java/com/smeme/server/util/message/ErrorMessage.java
src/main/java/com/smeme/server/util/message/ResponseMessage.java

- closed #53 
- 일기 삭제 기능 구현했습니다.
- 서비스 정책대로 Sofe Delete를 위해 isDelete = true 업데이트로 기능 구현했습니다.
- 에러핸들러에서 BAD_REQUEST -> NOT_FOUND 상태 값으로 하나 변경 및 추가했습니다.
- Default TimeZone 반영했습니다.
- 삭제된 일기(diary.isDeleted=true)는 조회 기능에서 호출되지 않도록 추가 처리했습니다.

[FEAT] 일기 삭제 API 구현

---

src/main/java/com/smeme/server/controller/TopicController.java
src/main/java/com/smeme/server/dto/topic/TopicResponseDTO.java
src/main/java/com/smeme/server/repository/TopicRepository.java
src/main/java/com/smeme/server/repository/topic/TopicCustomRepository.java
src/main/java/com/smeme/server/repository/topic/TopicRepository.java
src/main/java/com/smeme/server/repository/topic/TopicRepositoryImpl.java
src/main/java/com/smeme/server/service/DiaryService.java
src/main/java/com/smeme/server/service/TopicService.java
src/main/java/com/smeme/server/util/message/ResponseMessage.java

- closed #69 
- 랜덤 주제 조회 API 기능을 구현했습니다.
- TopicRepository 관련 QueryDSL을 추가하면서 package 추가 및 기존 TopicRepository 파일을 패키지 내로 위치 이동했습니다.
- 후에 랜덤주제 전체 조회 기능의 가능성을 생각하여 해당 uri를 `/api/v2/topics/random` 으로 변경했습니다. (+노션 반영)

[FEAT] 랜덤주제 조회 API 기능 구현

---

src/main/java/com/smeme/server/controller/ErrorHandler.java
src/main/java/com/smeme/server/controller/MemberController.java
src/main/java/com/smeme/server/dto/member/UpdateMemberRequestDTO.java
src/main/java/com/smeme/server/dto/member/UsernameValidator.java
src/main/java/com/smeme/server/dto/member/ValidUsername.java
src/main/java/com/smeme/server/model/Member.java
src/main/java/com/smeme/server/repository/MemberRepository.java
src/main/java/com/smeme/server/service/MemberService.java
src/main/java/com/smeme/server/util/message/ErrorMessage.java
src/main/java/com/smeme/server/util/message/ResponseMessage.java

- closed #29 
- 유저정보 설정 API 구현
- Member에 이용약관 동의 termAccepted 필드 추가 -> API 로직 추가
- 요청에 따라 Member에 fcm_token 추가

[FEAT] 회원가입 (유저정보 설정 API 구현)

---

src/main/java/com/smeme/server/controller/ScheduleController.java
src/main/java/com/smeme/server/model/Diary.java
src/main/java/com/smeme/server/repository/diary/DiaryCustomRepository.java
src/main/java/com/smeme/server/repository/diary/DiaryRepositoryImpl.java
src/main/java/com/smeme/server/service/DiaryService.java

- closed #80 
- 30일 전 삭제된 일기 영구 삭제 스케줄러 구현
- 매일 자정 스케줄러를 실행합니다.
- 삭제할 일기 관련 첨삭 데이터 삭제 및 member.getDiaries() 값을 업데이트합니다.

[FEAT] 30일 전 삭제된 일기 영구 삭제 스케줄러 구현

---

.github/workflows/cd.yml
.github/workflows/ci.yml

- closed #45 
- application.yml 파일과 application-oauth2.yml 파일을 병합함에 따라 oauth2 파일은 사용되지 않으므로 스크립트에서 삭제

[CHORE] application 파일 정리

---

src/main/java/com/smeme/server/config/SecurityConfig.java
src/main/java/com/smeme/server/controller/BadgeController.java
src/main/java/com/smeme/server/controller/BetaAuthController.java
src/main/java/com/smeme/server/dto/auth/beta/BetaTokenResponseDTO.java
src/main/java/com/smeme/server/model/SocialType.java
src/main/java/com/smeme/server/service/auth/BetaAuthService.java
src/main/java/com/smeme/server/util/message/ResponseMessage.java

- closed #106 
- 임시 토큰 API 발급 해주는 API를 구현했습니다.
- 만료 기간은 3주로 설정했습니다.
```JSON
{
"success": true,
"message": "임시토큰 발급 성공",
"data": {
"accessToken": "~"
}
}
```

[FEAT] 임시토큰 발급 API

---

src/main/java/com/smeme/server/service/MemberService.java

- closed #109 
- 학습 계획 설정 API가 에서 null일 경우 request body에서 학습시간이 없는 경우, 학습 계획 설정만 설정하도록 수정
- 베타 테스트 상에 API는 문제가 없으나, 릴리즈 시에 해당 API가 세 가지 상황을 커버 해야함.
1.  회원가입 시에,  초기 트레이닝 목표 설정 및 트레이닝 시간 설정
2. 마이페이지에서 트레이닝 목표 설정
3. 마이페이지에서 트레이닝 시간 설정
2번 , 3번 상황에서는 필요한 요청 외에는 null로 들어오는 request body data를 처리해줘야 하는데 좋은 설계인지?

[REFACTOR] 학습 계획 설정 API 개선

---

src/main/java/com/smeme/server/controller/BetaAuthController.java
src/main/java/com/smeme/server/dto/auth/SignInRequestDTO.java
src/main/java/com/smeme/server/dto/auth/SignInResponseDTO.java
src/main/java/com/smeme/server/dto/auth/beta/BetaSignInRequestDTO.java
src/main/java/com/smeme/server/dto/auth/beta/BetaTokenResponseDTO.java
src/main/java/com/smeme/server/dto/member/MemberGetResponseDTO.java
src/main/java/com/smeme/server/dto/member/MemberPushRequestDTO.java
src/main/java/com/smeme/server/model/Member.java
src/main/java/com/smeme/server/service/MemberService.java
src/main/java/com/smeme/server/service/auth/AuthService.java
src/main/java/com/smeme/server/service/auth/BetaAuthService.java

- closed #118 #117 
- 임시토큰 발급하는 API에서 fcmToken을 받아 DB에 저장하는 로직 추가
- 임시토큰 발급 API에서 welcome badge를 response로 내려줌
- 마이페이지 조회시에 최근 badge를 response로 내려줌. 단일 객체이므로, 기존 badges에서 badge로 컬럼명 변경

[REFACTOR] beta test를 위한 API response 개선

---

src/main/java/com/smeme/server/controller/MemberController.java
src/main/java/com/smeme/server/dto/training/TrainingTimeRequestDTO.java
src/main/java/com/smeme/server/service/MemberService.java

- closed #123 
- 현재 학습 계획 설정 API에서 day가 ""로 들어올 경우, 500 error를 뱉는다.
- > day가 ""로 들어오는 경우에도 요청은 200으로 이루어 지도록 API 로직 수정

[REFACTOR] day가 ""로 들어올 경우 학습계획 설정 API 로직 수정

---

src/main/java/com/smeme/server/dto/member/MemberPlanUpdateRequestDTO.java
src/main/java/com/smeme/server/service/MemberService.java

- closed #132 
- 학습 목표 타입만 request body에 들어오는 경우에도, 학습 목표가 업데이트 되도록 로직 수정

[REFACTOR] 학습 목표 타입만 request body에 들어오는 경우 처리

---

src/main/java/com/smeme/server/config/SwaggerConfig.java
src/main/java/com/smeme/server/controller/AuthController.java
src/main/java/com/smeme/server/controller/BadgeController.java
src/main/java/com/smeme/server/controller/CorrectionController.java
src/main/java/com/smeme/server/controller/DiaryController.java
src/main/java/com/smeme/server/controller/MemberController.java
src/main/java/com/smeme/server/controller/TopicController.java

- closed #138 
- `SwaggerConfig` class에 `@SecurityScheme`을 추가했습니다.
- Token 검증이 필요 없는 API를 제외하고, `@SecurityRequirement` 어노테이션을 추가했습니다.

[DOCS] Swagger에 Authorization Header 추가 가능하도록 수정

---

src/main/java/com/smeme/server/controller/MemberController.java
src/main/java/com/smeme/server/dto/auth/SignInResponseDTO.java
src/main/java/com/smeme/server/dto/badge/BadgeListResponseDTO.java
src/main/java/com/smeme/server/dto/member/MemberUpdateRequestDTO.java
src/main/java/com/smeme/server/dto/member/MemberUpdateResponseDTO.java
src/main/java/com/smeme/server/model/badge/MemberBadge.java
src/main/java/com/smeme/server/service/MemberService.java
src/main/java/com/smeme/server/service/auth/AuthService.java

- closed #137 
- 소셜로그인시에, member의 username 값이 null인지 아닌지 여부로 회원정보 입력 여부를 판단했습니다.
```
boolean isRegistered = false;
Member signedMember = getMemberBySocialAndSocialId(socialType, socialId);
if (nonNull(signedMember.getUsername())) {
isRegistered = true;
}
```
- 회원 정보 업데이트시에, `username`이 있는지 여부로 웰컴 뱃지 response 여부를 결정합니다.
- `MemberBadgeRepository`에 save method로 `MemberBadge`를 저장하고 조회 했을 때  DB에는 member_badge row가 한 개 저장되는데, 
`return MemberUpdateResponseDTO.of(member.getBadges());`로  API response를 확인하면 웰컴 뱃지가 2개 있는 것으로 나오네요. 영속성 컨텍스트 상에 MemberBadge entity가 2개 있어서 그런 것 같은데... 이유는 확실하지 않아서, save에서 saveAndFlush로 우선 구현했는데, 이 부분 review 부탁드립니다.

[REFACTOR] 소셜로그인, 회원정보 업데이트 API 수정

---

src/main/java/com/smeme/server/controller/BetaAuthController.java
src/main/java/com/smeme/server/controller/MemberController.java
src/main/java/com/smeme/server/dto/auth/SignInResponseDTO.java
src/main/java/com/smeme/server/dto/member/MemberGetResponseDTO.java
src/main/java/com/smeme/server/dto/training/TrainingTimeResponseDTO.java
src/main/java/com/smeme/server/model/badge/MemberBadge.java
src/main/java/com/smeme/server/repository/diary/DiaryRepository.java
src/main/java/com/smeme/server/repository/trainingTime/TrainingTimeRepository.java
src/main/java/com/smeme/server/service/CorrectionService.java
src/main/java/com/smeme/server/service/DiaryService.java
src/main/java/com/smeme/server/service/GoalService.java
src/main/java/com/smeme/server/service/MemberBadgeService.java
src/main/java/com/smeme/server/service/MemberService.java
src/main/java/com/smeme/server/service/TrainingTimeService.java
src/main/java/com/smeme/server/service/auth/AppleSignInService.java
src/main/java/com/smeme/server/service/auth/AuthService.java
src/main/java/com/smeme/server/service/auth/BetaAuthService.java
src/main/java/com/smeme/server/service/auth/KakaoSignInService.java
src/main/java/com/smeme/server/util/message/ErrorMessage.java
src/main/resources/static/docs/open-api-3.0.1.json

PR이 늦었습니다... 작업하면서 애매한 부분이 생겨서 처음에는 작업을 다 완료한 뒤에 PR을 올리고, 수정을 해보려고 했는데 너무 코드 변경이 많아져서 우선 일차적으로 PR을 올렸습니다.
논의해보고 수정한다음에 다시 작업진행하겠습니다.
- closed #165 #166 
- 진행하기로 한 API 리팩토링 방향대로 API 리팩토링을 진행했습니다.
- request DTO의 경우 파라미터 네이밍을 request, response DTO의 경우 네이밍을 response로 변경했습니다
- 한개의 service에서 해당 entity의 repository만을 의존하도록 코드를 변경했습니다.
- method 이름을 컨벤션에 맞춰서 변경했습니다.
- 연관관계 엔티티를 조회하는 경우에 id가 아니라 entity로 조회하도록 메소드를 변경했습니다.
- BetaAuthController는 사용하지 않기 때문에 `@Deprecated` 어노테이션을 붙여놨습니다.
- 미사용 import 문 제거 및 코드 스타일 정리를 진행했습니다.
#166 
여기에 작성했습니다.
논의사항 Comment 해주시면 맞춰서 코드 수정한 뒤에 다시 push하겠습니다 이후에 리뷰 해주시면 감사하겠습니다~!
- AppleService와 KakaoService의 API 요청 방법 통일은 추가로 리팩토링 진행하도록 하겠습니다.
1. Social Login Test
2. Member 학습 계획 설정 API
3. Token 재발급 API Test
4. Member 닉네임 중복검사 API Test
5. Member 유저네임 설정 API
6. Push 알람 동의여부 …

[REFACTOR] 윤한 담당 API 리팩토링

---

src/main/java/com/smeme/server/controller/AuthController.java
src/main/java/com/smeme/server/controller/BadgeController.java
src/main/java/com/smeme/server/controller/DiaryController.java
src/main/java/com/smeme/server/controller/GoalController.java
src/main/java/com/smeme/server/controller/MemberController.java
src/main/java/com/smeme/server/controller/TestController.java
src/main/java/com/smeme/server/controller/TopicController.java
src/main/java/com/smeme/server/dto/auth/SignInRequestDTO.java
src/main/java/com/smeme/server/dto/auth/SignInResponseDTO.java
src/main/java/com/smeme/server/dto/auth/beta/BetaSignInRequestDTO.java
src/main/java/com/smeme/server/dto/auth/beta/BetaTokenResponseDTO.java
src/main/java/com/smeme/server/dto/badge/BadgeListResponseDTO.java
src/main/java/com/smeme/server/dto/badge/BadgeResponseDTO.java
src/main/java/com/smeme/server/dto/diary/DiaryRequestDTO.java
src/main/java/com/smeme/server/dto/diary/DiaryResponseDTO.java
src/main/java/com/smeme/server/dto/member/MemberGetResponseDTO.java
src/main/java/com/smeme/server/dto/member/MemberNameResponseDTO.java
src/main/java/com/smeme/server/dto/member/MemberPlanUpdateRequestDTO.java
src/main/java/com/smeme/server/dto/member/MemberPushUpdateRequestDTO.java
src/main/java/com/smeme/server/dto/member/MemberUpdateRequestDTO.java
src/main/java/com/smeme/server/dto/member/MemberUpdateResponseDTO.java
src/main/java/com/smeme/server/dto/training/TrainingTimeResponseDTO.java

- closed #188 
- 구현 코드 내 스웨거 코드를 제거했습니다!

[DELETE] 스웨거 코드 삭제

---

src/main/java/com/smeme/server/dto/badge/BadgeListResponseDTO.java
src/main/java/com/smeme/server/repository/badge/BadgeCustomRepository.java
src/main/java/com/smeme/server/repository/badge/BadgeRepository.java
src/main/java/com/smeme/server/repository/badge/BadgeRepositoryImpl.java
src/main/java/com/smeme/server/service/BadgeService.java
src/main/resources/static/docs/open-api-3.0.1.json
src/test/java/com/smeme/server/controller/BadgeControllerTest.java
src/test/java/com/smeme/server/fixture/badge/BadgeFixture.java

- closed #192 
- 뱃지 전체 조회 기능에서 id 기준으로 정렬 처리 추가했습니다. (이름 순으로 피그마 형태가 안 나와서 id 기준으로 맞췄습니다!)
- API 테스트

[FIX] 뱃지 전체 조회 수정

---

src/main/java/com/smeme/server/repository/diary/DeletedDiaryRepository.java
src/main/java/com/smeme/server/service/DiaryService.java

- closed #194 
- 회원탈퇴 관련 500 에러 대응
- 회원이 임시 삭제한 일기 데이터를 추가로 삭제하도록 했습니다.

[FIX] 회원이 임시 삭제한 일기 데이터 삭제

---

smeem-external/src/main/java/com/smeem/external/oauth/kakao/KakaoService.java

- closed #214 
- Bearer String이 중복으로 들어가, 카카오 로그인에 실패하여 카카오 로그인이 실패하는 버그를 해결했습니다. 
- TestCode에 대해서는 논의가 안되어 있어, 우선 Postman 으로 API Test 진행했습니다!

[FIX] Bearer 중복으로 들어가는 코드 삭제

---

smeem-api/src/main/java/com/smeem/api/badge/controller/BadgeController.java
smeem-api/src/main/java/com/smeem/api/badge/controller/dto/response/BadgeListResponse.java
smeem-api/src/main/java/com/smeem/api/member/controller/MemberController.java

- closed #217 
- MemberController Response DTO를 ServiceResponse 에서 교체했습니다.
- BadgeController Response DTO를 ServiceResponse 에서 교체했습니다.
리팩토링 하면서 놓친 부분들이 조금씩 있네요 ...!

[FIX] Member, Badge Controller Response DTO 교체

---

smeem-api/src/main/java/com/smeem/api/config/SecurityConfig.java
smeem-api/src/main/java/com/smeem/api/version/api/VersionApi.java
smeem-api/src/main/java/com/smeem/api/version/api/VersionApiController.java
smeem-api/src/main/java/com/smeem/api/version/api/dto/response/ClientVersionGetResponse.java
smeem-api/src/main/java/com/smeem/api/version/service/VersionService.java
smeem-api/src/main/java/com/smeem/api/version/service/dto/response/ClientVersionGetServiceResponse.java
smeem-api/src/main/resources/application-dev.yml
smeem-api/src/main/resources/application-prod.yml
smeem-common/src/main/java/com/smeem/common/code/success/VersionSuccessCode.java
smeem-common/src/main/java/com/smeem/common/config/ValueConfig.java

- closed #234 
- iOS 심사 이슈로 앱 버전 조회 API 추가했습니다. (이후 안드에게도 상황 설명 후, 서버 버전 관리 사용한다고 하면 안드 버전도 추가할 예정)
- `고민점` : Service DTO 인자 값으로 ValueConfig를 넘겼습니다. 설정 값만 사용한다는 상황으로 판단한 방식입니다. 설정 값 하나씩 인자 값으로 넣어주는 방식도 고민했는데, 어떻게 생각하시나요!?
<br/>

[FEAT] 클라이언트 앱 버전 조회 API

---

smeem-api/src/main/java/com/smeem/api/auth/api/AuthApi.java
smeem-api/src/main/java/com/smeem/api/badge/api/BadgeApi.java
smeem-api/src/main/java/com/smeem/api/config/SwaggerConfig.java
smeem-api/src/main/java/com/smeem/api/diary/api/DiaryApi.java
smeem-api/src/main/java/com/smeem/api/member/api/MemberApi.java
smeem-api/src/main/java/com/smeem/api/test/api/TestApi.java
smeem-api/src/main/java/com/smeem/api/topic/api/TopicApi.java

- closed #262 
- 스웨거에서 토큰 인증 필터가 제대로 동작되지 않는 이슈를 해결했습니다.
- 테스트 과정에서 개별 헤더(Authorization)와 상관없이 무조건 전체 Authorize(자물쇠) 토큰 입력이 필수로 요구되어, 결과적으로 사용하지 않는 API별로 할당된 Authorization 입력 칸은 삭제했습니다.
<br/>

[FIX] 스웨거 토큰 이슈 해결

---

smeem-api/src/main/java/com/smeem/api/config/SecurityConfig.java
smeem-api/src/main/java/com/smeem/api/member/api/MemberApi.java
smeem-api/src/main/java/com/smeem/api/member/api/MemberController.java
smeem-api/src/main/java/com/smeem/api/member/api/dto/request/MemberPlanUpdateRequest.java
smeem-api/src/main/java/com/smeem/api/member/service/MemberService.java
smeem-api/src/main/java/com/smeem/api/member/service/dto/request/MemberUpdatePlanServiceRequest.java
smeem-api/src/main/java/com/smeem/api/plan/api/PlanApi.java
smeem-api/src/main/java/com/smeem/api/plan/api/PlanController.java
smeem-api/src/main/java/com/smeem/api/plan/api/dto/response/PlansAllGetResponse.java
smeem-api/src/main/java/com/smeem/api/plan/service/PlanService.java
smeem-api/src/main/java/com/smeem/api/plan/service/dto/response/PlansAllGetServiceResponse.java
smeem-api/src/main/java/com/smeem/api/support/ExceptionInterceptor.java
smeem-common/src/main/java/com/smeem/common/code/failure/PlanFailureCode.java
smeem-common/src/main/java/com/smeem/common/code/success/PlanSuccessCode.java
smeem-domain/src/main/java/com/smeem/domain/member/model/Member.java
smeem-domain/src/main/java/com/smeem/domain/plan/adapter/PlanFinder.java
smeem-domain/src/main/java/com/smeem/domain/plan/exception/PlanException.java
smeem-domain/src/main/java/com/smeem/domain/plan/repository/PlanRepository.java

- closed #261 
- 회원 학습 계획 수정 API에서 Request에 Null 가능한 PlanId 추가했습니다.
- 플랜 데이터를 전체 조회하는 API를 개발했습니다.
<br/>

[FEAT] 플랜 전체 조회 API

---

smeem-api/src/main/java/com/smeem/api/member/api/MemberController.java
smeem-api/src/main/java/com/smeem/api/member/api/dto/response/MemberPerformanceGetResponse.java
smeem-api/src/main/java/com/smeem/api/member/api/dto/response/MemberPlanGetResponse.java
smeem-api/src/main/java/com/smeem/api/plan/api/PlanController.java
smeem-api/src/main/java/com/smeem/api/plan/api/dto/response/PlansAllGetResponse.java
smeem-domain/src/main/java/com/smeem/domain/plan/adapter/PlanFinder.java
smeem-domain/src/main/java/com/smeem/domain/plan/repository/PlanRepository.java

- closed #272 
- 플랜 전체 목록 조회 기능에서 정렬 조건 (id 오름차순) 추가했습니다.
- 추가로 컨벤션을 통일하기 위해 일부 of 메서드명을 from으로 수정했습니다.

[FIX] 플랜 조회 정렬 조건 추가

---

smeem-api/src/main/java/com/smeem/api/badge/service/BadgeService.java
smeem-domain/src/main/java/com/smeem/domain/member/adapter/memberbadge/MemberBadgeCounter.java
smeem-domain/src/main/java/com/smeem/domain/member/adapter/memberbadge/MemberBadgeFinder.java
smeem-domain/src/main/java/com/smeem/domain/member/repository/MemberBadgeRepository.java

- closed #289 
- 배지 획득까지 남은 횟수를 계산하는 로직을 수정했습니다.
- 일기를 1개 작성한 회원 기준 10개 카운팅 배지 획득까지 9번 남았음 데이터를 반환하는 결과를 이미지를 통해 확인할 수 있습니다.

[FIX] 배지 획득까지 남은 횟수 반환 로직 수정

---

smeem-api/src/test/java/com/smeem/diary/service/DiaryCommandServiceIntegrationTest.java
smeem-api/src/test/java/com/smeem/support/ServiceIntegrationTest.java
smeem-api/src/test/java/com/smeem/support/fixture/MemberFixture.java
smeem-domain/src/main/java/com/smeem/domain/diary/repository/DiaryRepository.java
smeem-domain/src/main/java/com/smeem/domain/member/model/Member.java

- closed #287 
- 오늘 일기를 작성하지 않은 회원은 일기를 생성할 수 있고, 일기 연속 작성 수가 업데이트된다.
- 오늘 일기를 작성한 회원은 일기를 작성할 수 없다.
- 테스트 코드 설정 관련 [에러](https://unhosted.tistory.com/77)가 발생하여 대응했습니다.
- 노션에 정리한 테스트 코드 컨벤션 참고하여 테스트 코드를 작성했습니다.
- MemberFixture를 생성할 때 NotNullable한 칼럼은 기본값을 지정했습니다.
- Description 항목 내 2가지 기능을 테스트 했습니다.
- 부족한 점 또는 관련 논의할 사항이 있다면 리뷰 추가해주시면 감사하겠습니다!

[TEST] 일기 저장 관련 테스트 코드 작성

---

smeem-api/src/main/java/com/smeem/api/version/service/dto/response/ClientVersionGetServiceResponse.java
smeem-api/src/main/resources/application-dev.yml
smeem-api/src/main/resources/application-prod.yml
smeem-api/src/test/resources/application-test.yml
smeem-common/src/main/java/com/smeem/common/config/ValueConfig.java

- closed #298 
- 버전 조회 내 안드로이드 정보 추가

[ADD] 안드로이드 버전 추가

---

smeem-api/src/test/java/com/smeem/goal/service/GoalServiceIntegrationTest.java
smeem-api/src/test/java/com/smeem/support/fixture/GoalFixture.java

- closed #285 
- 성공 케이스에 대해서 GoalService test code를 작성했습니다.

[TEST] GoalService 테스트 코드 작성

---

.github/workflows/ci.yml
README.md

docs: Update README.md

---

smeem-common/src/main/java/com/smeem/common/exception/ExceptionCode.java
smeem-input-http/build.gradle
smeem-input-http/src/main/java/com/smeem/http/aspect/DuplicateRequestAspect.java
smeem-input-http/src/main/java/com/smeem/http/controller/MemberBadgeV3Api.java
smeem-input-http/src/main/java/com/smeem/http/controller/docs/MemberBadgeV3ApiDocs.java

- closed #290 
- 중복 요청을 막기 위한 AOP를 추가했습니다.
- [참고 아티클](https://soobysu.tistory.com/m/125)
- 위 이미지처럼 같은 요청에 대해 중복으로 처리되는 경우가 간혹 있음

feat: 중복 요청 방지를 위한 AOP 설정

---

.github/workflows/deploy-dev.yml
script/deploy.sh

- closed #344 
- 블루그린 배포 전략을 활용하여 무중단 배포 환경을 구축합니다. (dev 서버 재구축 후 테스트 예정)

fix: 블루그린 배포 전략 적용

---

.github/workflows/ci.yml
.github/workflows/deploy-dev.yml
smeem-application/src/main/java/com/smeem/application/domain/diary/Diary.java
smeem-application/src/main/java/com/smeem/application/domain/diary/DiaryService.java
smeem-application/src/main/java/com/smeem/application/port/input/DiaryUseCase.java
smeem-application/src/main/java/com/smeem/application/port/input/dto/request/diary/WriteDiaryRequest.java
smeem-application/src/main/java/com/smeem/application/port/input/dto/response/diary/RetrieveDiaryResponse.java
smeem-application/src/main/java/com/smeem/application/port/output/persistence/CorrectionPort.java
smeem-application/src/main/java/com/smeem/application/port/output/persistence/DiaryPort.java
smeem-application/src/main/java/com/smeem/application/port/output/persistence/TopicPort.java
smeem-common/src/main/java/com/smeem/common/exception/SmeemException.java
smeem-input-http/src/main/java/com/smeem/http/config/SecurityConfig.java
smeem-input-http/src/main/java/com/smeem/http/controller/DiaryApi.java
smeem-input-http/src/main/java/com/smeem/http/controller/docs/DiaryApiDocs.java
smeem-output-cache/redis/src/main/java/com/smeem/output/cache/redis/adapter/RedisCacheAdapter.java
smeem-output-persistence/postgresql/src/main/java/com/smeem/persistence/postgresql/adapter/CorrectionAdapter.java
smeem-output-persistence/postgresql/src/main/java/com/smeem/persistence/postgresql/adapter/DiaryAdapter.java
smeem-output-persistence/postgresql/src/main/java/com/smeem/persistence/postgresql/adapter/TopicAdapter.java
smeem-output-persistence/postgresql/src/main/java/com/smeem/persistence/postgresql/persistence/entity/CorrectionEntity.java
smeem-output-persistence/postgresql/src/main/java/com/smeem/persistence/postgresql/persistence/entity/DiaryEntity.java
smeem-output-persistence/postgresql/src/main/java/com/smeem/persistence/postgresql/persistence/entity/VisitEntity.java
smeem-output-persistence/postgresql/src/main/java/com/smeem/persistence/postgresql/persistence/repository/diary/CorrectionRepository.java
smeem-output-persistence/postgresql/src/main/resources/postgres-config/application-dev.yml
smeem-output-persistence/postgresql/src/main/resources/postgres-config/application-prod.yml

- closed #347 #346 
- dev 서버 재구축

infra: dev 서버 재구축

---

smeem-application/src/main/java/com/smeem/application/domain/survey/DissatisfactionType.java
smeem-application/src/main/java/com/smeem/application/domain/survey/SurveyService.java
smeem-application/src/main/java/com/smeem/application/port/input/dto/request/survey/CoachingSurveyRequest.java
smeem-common/src/main/java/com/smeem/common/config/DiscordProperties.java
smeem-common/src/main/java/com/smeem/common/exception/ExceptionCode.java
smeem-common/src/main/java/com/smeem/common/logger/LoggerType.java
smeem-common/src/main/java/com/smeem/common/logger/LoggingMessage.java
smeem-common/src/main/java/com/smeem/common/logger/discord/DiscordHookLogger.java
smeem-common/src/main/resources/common-config/application-dev.yml
smeem-common/src/main/resources/common-config/application-local.yml
smeem-common/src/main/resources/common-config/application-prod.yml

- closed #367 
- 만족도 조사 결과 전송 시 디스코드에도 전송되도록 연동
- infisical에 웹훅 url 추가 및 yml 파일 수정
- dissatisfaction type 요청 값 중 유효하지 않은 값 들어왔을 때 cors에러가 아닌 exception 발생하도록 dto에 로직 추가

chore: discord logging for coaching survey
